### ISSUE TITLE
yarn build時にエラー

### ISSUE THREAD

**Issue by 0x070696E65** [OPENSPHERE-Inc/metal-on-symbol#12]
タイトル通り、yarn でのbuild時に
```
../../../node_modules/@types/express-serve-static-core/index.d.ts:589:18 - error TS2430: Interface 'Response<ResBody, Locals, StatusCode>' incorrectly extends interface 'ServerResponse<IncomingMessage>'.
  Types of property 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> | undefined' is not assignable to type 'IncomingMessage'.
      Type 'undefined' is not assignable to type 'IncomingMessage'.

589 export interface Response<
```
というエラーになりました

tsconfig.jsonのcompilerOptionsに`"skipLibCheck": true`を追記すると消えました。
これはあまり良い回避策ではないようですが…
```
yarn -v
1.22.18
```
以上、報告させていただきます！

**Comment by hanatyan128** [comment]
フレッシュな環境に clone して build しても再現せず・・・

**Comment by hanatyan128** [comment]
環境依存な気がします！ tsc が変なところにパス通ってるとか

**Comment by 0x070696E65** [comment]
まず解決方法でやはり
`"skipLibCheck": true`はダメだと思い
`npm i -D @types/express-serve-static-core`で問題なくビルドが通りました。

で、環境ですが
Mac Apple M1 Pro
OS 12.2.1
node v16.11.1
他に何が必要か分からず、指示いただければ調べます！

もしかするとM1が問題かもです、色々違うことが多いので…
