### ISSUE TITLE
RepositoryFactoryHttp生成時にRepositoryFactoryConfigを指定したい（browserで使用するWebSocket対応）

### ISSUE THREAD

**Issue by xembook** [OPENSPHERE-Inc/metal-on-symbol#17]
以下で生成しているRepositoryFactoryHttpですが、

https://github.com/OPENSPHERE-Inc/metal-on-symbol/blob/166b6b5533123048a2272a5d13cc2b59f59c3769/src/services/symbol.ts#L99

コンストラクタで第二引数で指定できる、RepositoryFactoryConfigを指定したいです。

https://github.com/symbol/symbol-sdk-typescript-javascript/blob/f094ab4be762986c593b0dbb1cb9cd4791977a33/src/infrastructure/RepositoryFactoryHttp.ts#L82

理由はbrowserでwebsocketを使用する場合に
websocketInjectedに`WebSocket`を指定する必要があります。

https://github.com/symbol/symbol-sdk-typescript-javascript/blob/f9f12a6eab3df40582d7583f6b1835513dd4b3cf/src/infrastructure/RepositoryFactoryConfig.ts#L36

browserではこんな感じで使用します。

https://github.com/xembook/quick_learning_symbol/blob/main/10_observer.md#101-%E3%83%AA%E3%82%B9%E3%83%8A%E3%83%BC%E8%A8%AD%E5%AE%9A

ご検討よろしくお願いします。

**Comment by hanatyan128** [comment]
SymbolService.init() で RepositoryFactoryConfig を渡せるようにしました。問題あればリオープンしてください！
