### ISSUE TITLE
browserifyでjs化して使用したい

### ISSUE THREAD

**Issue by xembook** [OPENSPHERE-Inc/metal-on-symbol#8]
非常に興味深いプロトコルの提案、ありがとうございます。
metal-on-symbolをcliではなく、jsとしてhtmlの中で使用してみたいと思っています。

browserifyで変換してみると、jsファイルには変換できましたが、

```
metal = require("/node_modules/metal-on-symbol");
```

と読み込んでみると以下のようなメッセージが表示されました。

```
Metal CLI version 1.0

Usage:        $ metal command [options]
Commands:
  fetch       Fetch on-chain metal and decode into file.
  forge       Upload the metal onto blockchain.
  reinforce   Cosigning forge/scrap intermediate transactions for multisig resolution.
  scrap       Scrap the metal on blockchain.
  verify      Verify off-chain file vs on-chain metal.
Options:
  -h, --help  Show command line usage.
```

どうやら読み込み時に引数を適切に指定しないとcommandがうまく使えないようです。
symbol-sdk(ver2系)をbrowserifyした場合、以下のような感じでメソッドを使えるようになります。

```js
sym = require("/node_modules/symbol-sdk");
repo = new sym.RepositoryFactoryHttp(NODE);
accountRepo = repo.createAccountRepository();
```

このような感じでmeta-on-symbolを使うことは可能でしょうか？

**Comment by hanatyan128** [comment]
まだ自分で試してなくて、ドキュメントも用意できてないんですが、
取り急ぎ export 関連を適切に整備して ver.0.1.10 をプッシュしました。

metal-on-symbol をインポートすると

MetalService.*
SymbolService.*

※簡単なサンプルは test/util.ts

metal-on-symbol/cli をインポートすると

FetchCLI.main(argv: string[])
ForgeCLI.main(argv: string[])
ReinforceCLI.main(argv: string[])
ScrapCLI.main(argv: string[])
VerifyCLI.main(argv: string[])

※argv には、各コマンドの引数を配列にして渡してください。

がそれぞれ使えるようになると思います。
（ただし、CLI は fs とか使ってるのでブラウザでの動作はしないかと？）

**Comment by hanatyan128** [comment]
README に SDK ドキュメントを追加しました。
#13

**Comment by xembook** [comment]
ありがとうございます！
とりあえずbrowserifyして生成したjsをrequireすると
SymbolService、MetalServiceが使えるようになっていることが確認できました。
引き続き、いろいろ試してみたいと思います。
